server:
  port: 18081

spring:
  profiles:
    active: local
  application:
    name: datafactory-task

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.datafactory.task.domain
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  