server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: datafactory-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: datafactory-task
              uri: lb://datafactory-task
              predicates:
                - Path=/task/**
              filters:
                - StripPrefix=1
            - id: datafactory-executor
              uri: lb://datafactory-executor
              predicates:
                - Path=/executor/**
              filters:
                - StripPrefix=1
            - id: datafactory-datasource
              uri: lb://datafactory-datasource
              predicates:
                - Path=/datasource/**
              filters:
                - StripPrefix=1
            - id: datafactory-openapi
              uri: lb://datafactory-openapi
              predicates:
                - Path=/openapi/**
              filters:
                - StripPrefix=1
            - id: datafactory-log
              uri: lb://datafactory-executor
              predicates:
                - Path=/log/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
